export const evaluations = [
  {
    id: 1048,
    name: "Carlos Méndez",
    document: "1023456789",
    score: 842,
    level: "Muy bajo",
    tone: "positive",
    date: "19 sep, 14:32",
  },
  {
    id: 1047,
    name: "Lucía Fernández",
    document: "1098765432",
    score: 715,
    level: "Bajo",
    tone: "accent",
    date: "19 sep, 13:48",
  },
  {
    id: 1046,
    name: "Jorge Salazar",
    document: "1055667788",
    score: 582,
    level: "Medio",
    tone: "warning",
    date: "19 sep, 11:15",
  },
  {
    id: 1045,
    name: "Marta Ibáñez",
    document: "1011223344",
    score: 418,
    level: "Alto",
    tone: "negative",
    date: "18 sep, 16:40",
  },
  {
    id: 1044,
    name: "Diego Paredes",
    document: "1077889900",
    score: 268,
    level: "Muy alto",
    tone: "critical",
    date: "18 sep, 15:21",
  },
] as const;

export const applicants = [
  {
    name: "Carlos Méndez",
    document: "1023456789",
    income: 6200000,
    debt: 1450000,
    history: "BUENO",
    arrears: 0,
  },
  {
    name: "Lucía Fernández",
    document: "1098765432",
    income: 4100000,
    debt: 1750000,
    history: "REGULAR",
    arrears: 1,
  },
  {
    name: "Jorge Salazar",
    document: "1055667788",
    income: 3300000,
    debt: 2200000,
    history: "REGULAR",
    arrears: 2,
  },
] as const;

export const riskVariables = [
  {
    id: 1,
    name: "Ingresos mensuales",
    code: "INGRESOS_MENSUALES",
    type: "Numérica",
    description: "Capacidad mensual de generación de ingresos.",
    active: true,
  },
  {
    id: 2,
    name: "Nivel de endeudamiento",
    code: "NIVEL_ENDEUDAMIENTO",
    type: "Numérica",
    description: "Relación entre deudas e ingresos del solicitante.",
    active: true,
  },
  {
    id: 3,
    name: "Número de moras",
    code: "NUMERO_MORAS",
    type: "Numérica",
    description: "Cantidad de obligaciones reportadas en mora.",
    active: true,
  },
  {
    id: 4,
    name: "Historial crediticio",
    code: "HISTORIAL_CREDITICIO",
    type: "Categórica",
    description: "Comportamiento histórico de pago.",
    active: true,
  },
  {
    id: 5,
    name: "Antigüedad laboral",
    code: "ANTIGUEDAD_LABORAL",
    type: "Numérica",
    description: "Tiempo de permanencia laboral expresado en años.",
    active: false,
  },
] as const;

export const scoringRules = [
  {
    id: 11,
    variable: "Ingresos mensuales",
    operator: ">",
    value: "$4.000.000",
    points: 200,
    active: true,
  },
  {
    id: 12,
    variable: "Nivel de endeudamiento",
    operator: "<",
    value: "30%",
    points: 200,
    active: true,
  },
  {
    id: 13,
    variable: "Historial crediticio",
    operator: "=",
    value: "BUENO",
    points: 250,
    active: true,
  },
  { id: 14, variable: "Número de moras", operator: "=", value: "0", points: 200, active: true },
  {
    id: 15,
    variable: "Antigüedad laboral",
    operator: ">",
    value: "3 años",
    points: 100,
    active: false,
  },
] as const;
