/* eslint-disable prettier/prettier */
import { createFileRoute } from "@tanstack/react-router";
import { Plus, Scale } from "lucide-react";
import { useState, type FormEvent } from "react";
import { PageHeader, Panel, Field } from "@/components/page";
import { Button } from "@/components/ui/button";
import { api, ApiRequestError, isApiConfigured, scoringRuleSchema, type ScoringRuleInput } from "@/lib/api";

export const Route = createFileRoute("/reglas")({ head: () => ({ meta: [
  { title: "Reglas de scoring — Veridica" }, { name: "description", content: "Reglas que convierten variables de riesgo en puntuaciones crediticias." }, { property: "og:title", content: "Reglas de scoring — Veridica" }, { property: "og:description", content: "Reglas que convierten variables de riesgo en puntuaciones crediticias." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
] }), component: RulesPage });

function RulesPage() {
  const [form, setForm] = useState<ScoringRuleInput>({ idRiesgo: 1, operador: ">", valorCondicion: "", puntaje: 0 });
  const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); const parsed = scoringRuleSchema.safeParse(form); if (!parsed.success) { setError(parsed.error.issues[0]?.message ?? "Revisa los datos"); return; } setLoading(true); setError(""); setMessage(""); try { if (!isApiConfigured) { setError("Configura VITE_API_BASE_URL para guardar reglas."); return; } const created = await api.createScoringRule(parsed.data); setMessage(`Regla ${created.idRegla} creada correctamente.`); setForm({ ...form, valorCondicion: "", puntaje: 0 }); } catch (requestError) { setError(requestError instanceof ApiRequestError ? requestError.message : "No fue posible crear la regla."); } finally { setLoading(false); } }
  return <><PageHeader eyebrow="Configuración del modelo" title="Reglas de scoring" description="Configura cómo cada condición suma o resta puntos. Solo se aplican reglas activas asociadas a variables activas." /><div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_23rem]">
    <Panel className="overflow-hidden"><div className="border-b border-border px-5 py-4"><h2 className="font-display text-lg font-bold">Reglas configuradas</h2><p className="text-sm text-muted-foreground">La consulta de reglas existentes aún no está publicada por el backend.</p></div><div className="grid min-h-56 place-items-center p-6 text-center text-sm text-muted-foreground">Crea una regla desde el formulario. El motor validará la variable activa, duplicados y el rango de puntos.</div></Panel>
    <Panel className="h-fit p-5"><div className="mb-5 flex items-center gap-3"><span className="grid size-10 place-items-center rounded-lg bg-accent-soft text-primary"><Scale className="size-5" /></span><div><h2 className="font-display font-bold">Nueva regla</h2><p className="text-xs text-muted-foreground">Se guarda en el motor de scoring.</p></div></div>{message && <p className="mb-4 rounded-lg bg-positive-soft p-3 text-sm text-positive" role="status">{message}</p>}{error && <p className="mb-4 rounded-lg bg-destructive-soft p-3 text-sm text-destructive" role="alert">{error}</p>}<form onSubmit={submit} className="space-y-4"><Field label="ID de variable de riesgo" htmlFor="rule-variable"><input id="rule-variable" type="number" min="1" step="1" className="form-control" value={form.idRiesgo} onChange={(e) => setForm({ ...form, idRiesgo: Number(e.target.value) })} /></Field><div className="grid grid-cols-[6rem_minmax(0,1fr)] gap-3"><Field label="Operador" htmlFor="operator"><select id="operator" className="form-control" value={form.operador} onChange={(e) => setForm({ ...form, operador: e.target.value as ScoringRuleInput["operador"] })}>{["=", ">", ">=", "<", "<="].map((item) => <option key={item}>{item}</option>)}</select></Field><Field label="Valor" htmlFor="value"><input id="value" className="form-control" value={form.valorCondicion} onChange={(e) => setForm({ ...form, valorCondicion: e.target.value })} /></Field></div><Field label="Puntaje" htmlFor="points"><input id="points" type="number" min="-100" max="100" step="1" className="form-control" value={form.puntaje} onChange={(e) => setForm({ ...form, puntaje: Number(e.target.value) })} /></Field><Button className="w-full" type="submit" disabled={loading}><Plus className="size-4" />{loading ? "Guardando…" : "Crear regla"}</Button></form></Panel>
  </div></>;
}