/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EvaluacionesRouteImport } from './routes/evaluaciones'
import { Route as InformesRouteImport } from './routes/informes'
import { Route as ReglasRouteImport } from './routes/reglas'
import { Route as SolicitantesRouteImport } from './routes/solicitantes'
import { Route as VariablesRouteImport } from './routes/variables'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluacionesRoute = EvaluacionesRouteImport.update({
  id: '/evaluaciones',
  path: '/evaluaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const InformesRoute = InformesRouteImport.update({
  id: '/informes',
  path: '/informes',
  getParentRoute: () => rootRouteImport,
} as any)
const ReglasRoute = ReglasRouteImport.update({
  id: '/reglas',
  path: '/reglas',
  getParentRoute: () => rootRouteImport,
} as any)
const SolicitantesRoute = SolicitantesRouteImport.update({
  id: '/solicitantes',
  path: '/solicitantes',
  getParentRoute: () => rootRouteImport,
} as any)
const VariablesRoute = VariablesRouteImport.update({
  id: '/variables',
  path: '/variables',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/evaluaciones': typeof EvaluacionesRoute
  '/informes': typeof InformesRoute
  '/reglas': typeof ReglasRoute
  '/solicitantes': typeof SolicitantesRoute
  '/variables': typeof VariablesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/evaluaciones': typeof EvaluacionesRoute
  '/informes': typeof InformesRoute
  '/reglas': typeof ReglasRoute
  '/solicitantes': typeof SolicitantesRoute
  '/variables': typeof VariablesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/evaluaciones': typeof EvaluacionesRoute
  '/informes': typeof InformesRoute
  '/reglas': typeof ReglasRoute
  '/solicitantes': typeof SolicitantesRoute
  '/variables': typeof VariablesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/evaluaciones'
    | '/informes'
    | '/reglas'
    | '/solicitantes'
    | '/variables'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/evaluaciones'
    | '/informes'
    | '/reglas'
    | '/solicitantes'
    | '/variables'
  id:
    | '__root__'
    | '/'
    | '/evaluaciones'
    | '/informes'
    | '/reglas'
    | '/solicitantes'
    | '/variables'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EvaluacionesRoute: typeof EvaluacionesRoute
  InformesRoute: typeof InformesRoute
  ReglasRoute: typeof ReglasRoute
  SolicitantesRoute: typeof SolicitantesRoute
  VariablesRoute: typeof VariablesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluaciones': {
      id: '/evaluaciones'
      path: '/evaluaciones'
      fullPath: '/evaluaciones'
      preLoaderRoute: typeof EvaluacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informes': {
      id: '/informes'
      path: '/informes'
      fullPath: '/informes'
      preLoaderRoute: typeof InformesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reglas': {
      id: '/reglas'
      path: '/reglas'
      fullPath: '/reglas'
      preLoaderRoute: typeof ReglasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solicitantes': {
      id: '/solicitantes'
      path: '/solicitantes'
      fullPath: '/solicitantes'
      preLoaderRoute: typeof SolicitantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/variables': {
      id: '/variables'
      path: '/variables'
      fullPath: '/variables'
      preLoaderRoute: typeof VariablesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EvaluacionesRoute: EvaluacionesRoute,
  InformesRoute: InformesRoute,
  ReglasRoute: ReglasRoute,
  SolicitantesRoute: SolicitantesRoute,
  VariablesRoute: VariablesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
