/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CrearCuentaRouteImport } from './routes/crear-cuenta'
import { Route as IniciarSesionRouteImport } from './routes/iniciar-sesion'
import { Route as PanelRouteRouteImport } from './routes/panel/route'
import { Route as PanelIndexRouteImport } from './routes/panel/index'
import { Route as PanelEvaluacionesRouteImport } from './routes/panel/evaluaciones'
import { Route as PanelInformesRouteImport } from './routes/panel/informes'
import { Route as PanelReglasRouteImport } from './routes/panel/reglas'
import { Route as PanelSolicitantesRouteImport } from './routes/panel/solicitantes'
import { Route as PanelVariablesRouteImport } from './routes/panel/variables'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrearCuentaRoute = CrearCuentaRouteImport.update({
  id: '/crear-cuenta',
  path: '/crear-cuenta',
  getParentRoute: () => rootRouteImport,
} as any)
const IniciarSesionRoute = IniciarSesionRouteImport.update({
  id: '/iniciar-sesion',
  path: '/iniciar-sesion',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelRouteRoute = PanelRouteRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelIndexRoute = PanelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PanelRouteRoute,
} as any)
const PanelEvaluacionesRoute = PanelEvaluacionesRouteImport.update({
  id: '/evaluaciones',
  path: '/evaluaciones',
  getParentRoute: () => PanelRouteRoute,
} as any)
const PanelInformesRoute = PanelInformesRouteImport.update({
  id: '/informes',
  path: '/informes',
  getParentRoute: () => PanelRouteRoute,
} as any)
const PanelReglasRoute = PanelReglasRouteImport.update({
  id: '/reglas',
  path: '/reglas',
  getParentRoute: () => PanelRouteRoute,
} as any)
const PanelSolicitantesRoute = PanelSolicitantesRouteImport.update({
  id: '/solicitantes',
  path: '/solicitantes',
  getParentRoute: () => PanelRouteRoute,
} as any)
const PanelVariablesRoute = PanelVariablesRouteImport.update({
  id: '/variables',
  path: '/variables',
  getParentRoute: () => PanelRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/panel': typeof PanelRouteRouteWithChildren
  '/crear-cuenta': typeof CrearCuentaRoute
  '/iniciar-sesion': typeof IniciarSesionRoute
  '/panel/evaluaciones': typeof PanelEvaluacionesRoute
  '/panel/informes': typeof PanelInformesRoute
  '/panel/reglas': typeof PanelReglasRoute
  '/panel/solicitantes': typeof PanelSolicitantesRoute
  '/panel/variables': typeof PanelVariablesRoute
  '/panel/': typeof PanelIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/crear-cuenta': typeof CrearCuentaRoute
  '/iniciar-sesion': typeof IniciarSesionRoute
  '/panel/evaluaciones': typeof PanelEvaluacionesRoute
  '/panel/informes': typeof PanelInformesRoute
  '/panel/reglas': typeof PanelReglasRoute
  '/panel/solicitantes': typeof PanelSolicitantesRoute
  '/panel/variables': typeof PanelVariablesRoute
  '/panel': typeof PanelIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/panel': typeof PanelRouteRouteWithChildren
  '/crear-cuenta': typeof CrearCuentaRoute
  '/iniciar-sesion': typeof IniciarSesionRoute
  '/panel/evaluaciones': typeof PanelEvaluacionesRoute
  '/panel/informes': typeof PanelInformesRoute
  '/panel/reglas': typeof PanelReglasRoute
  '/panel/solicitantes': typeof PanelSolicitantesRoute
  '/panel/variables': typeof PanelVariablesRoute
  '/panel/': typeof PanelIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/panel'
    | '/crear-cuenta'
    | '/iniciar-sesion'
    | '/panel/evaluaciones'
    | '/panel/informes'
    | '/panel/reglas'
    | '/panel/solicitantes'
    | '/panel/variables'
    | '/panel/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/crear-cuenta'
    | '/iniciar-sesion'
    | '/panel/evaluaciones'
    | '/panel/informes'
    | '/panel/reglas'
    | '/panel/solicitantes'
    | '/panel/variables'
    | '/panel'
  id:
    | '__root__'
    | '/'
    | '/panel'
    | '/crear-cuenta'
    | '/iniciar-sesion'
    | '/panel/evaluaciones'
    | '/panel/informes'
    | '/panel/reglas'
    | '/panel/solicitantes'
    | '/panel/variables'
    | '/panel/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PanelRouteRoute: typeof PanelRouteRouteWithChildren
  CrearCuentaRoute: typeof CrearCuentaRoute
  IniciarSesionRoute: typeof IniciarSesionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crear-cuenta': {
      id: '/crear-cuenta'
      path: '/crear-cuenta'
      fullPath: '/crear-cuenta'
      preLoaderRoute: typeof CrearCuentaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iniciar-sesion': {
      id: '/iniciar-sesion'
      path: '/iniciar-sesion'
      fullPath: '/iniciar-sesion'
      preLoaderRoute: typeof IniciarSesionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel': {
      id: '/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof PanelRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel/': {
      id: '/panel/'
      path: '/'
      fullPath: '/panel/'
      preLoaderRoute: typeof PanelIndexRouteImport
      parentRoute: typeof PanelRouteRoute
    }
    '/panel/evaluaciones': {
      id: '/panel/evaluaciones'
      path: '/evaluaciones'
      fullPath: '/panel/evaluaciones'
      preLoaderRoute: typeof PanelEvaluacionesRouteImport
      parentRoute: typeof PanelRouteRoute
    }
    '/panel/informes': {
      id: '/panel/informes'
      path: '/informes'
      fullPath: '/panel/informes'
      preLoaderRoute: typeof PanelInformesRouteImport
      parentRoute: typeof PanelRouteRoute
    }
    '/panel/reglas': {
      id: '/panel/reglas'
      path: '/reglas'
      fullPath: '/panel/reglas'
      preLoaderRoute: typeof PanelReglasRouteImport
      parentRoute: typeof PanelRouteRoute
    }
    '/panel/solicitantes': {
      id: '/panel/solicitantes'
      path: '/solicitantes'
      fullPath: '/panel/solicitantes'
      preLoaderRoute: typeof PanelSolicitantesRouteImport
      parentRoute: typeof PanelRouteRoute
    }
    '/panel/variables': {
      id: '/panel/variables'
      path: '/variables'
      fullPath: '/panel/variables'
      preLoaderRoute: typeof PanelVariablesRouteImport
      parentRoute: typeof PanelRouteRoute
    }
  }
}

interface PanelRouteRouteChildren {
  PanelEvaluacionesRoute: typeof PanelEvaluacionesRoute
  PanelInformesRoute: typeof PanelInformesRoute
  PanelReglasRoute: typeof PanelReglasRoute
  PanelSolicitantesRoute: typeof PanelSolicitantesRoute
  PanelVariablesRoute: typeof PanelVariablesRoute
  PanelIndexRoute: typeof PanelIndexRoute
}

const PanelRouteRouteChildren: PanelRouteRouteChildren = {
  PanelEvaluacionesRoute: PanelEvaluacionesRoute,
  PanelInformesRoute: PanelInformesRoute,
  PanelReglasRoute: PanelReglasRoute,
  PanelSolicitantesRoute: PanelSolicitantesRoute,
  PanelVariablesRoute: PanelVariablesRoute,
  PanelIndexRoute: PanelIndexRoute,
}

const PanelRouteRouteWithChildren = PanelRouteRoute._addFileChildren(
  PanelRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PanelRouteRoute: PanelRouteRouteWithChildren,
  CrearCuentaRoute: CrearCuentaRoute,
  IniciarSesionRoute: IniciarSesionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
